# print("hello\nworld")
# print("diamondshah")

#string Operations
name="diamond Kumar"
print(name[0])
print(name[0:7])
print(name[0:8:2])
print(name[::2])
print(name[-1])
print(name[::-1])
print(len(name))
print(name.lower())
print(name.upper())
print(name.replace("Kumar","Shah"))
print(name.split(" "))
print(name.capitalize())
print(name.title())   
print(name.count("a"))
print(name.find("Kumar"))
print(name.index("Kumar"))
print(name.isalnum())
print(name.isalpha())
print(name.endswith("r"))
print(name.startswith("d"))